service: start-stop-aws-rds-tags

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  role: arn:aws:iam::123456789101112:role/start-stop-rds-ec2
  environment:
    START_TIME: '07:00'
    STOP_TIME: '22:00'
    TIMEZONE: 'America/Sao_Paulo'
  logs:
    level: INFO

functions:
  start-stop-rds:
    handler: main.lambda_handler
    memorySize: 256
    events:
      - schedule:
          rate: cron(1 10,2 ? * MON-FRI *)
          enabled: true

package:
  include:
    - main.py
